// Auto-generated by scripts/buildM8Graph.ts from linkBetweenM8Pages.log
export type Direction = 'up' | 'down' | 'left' | 'right'
export interface Edge {
    to: string
    dir: Direction
}
export const M8_GRAPH: Record<string, Edge[]> = {
    chainspcvpit: [
        { to: 'mixerspcvxpit', dir: 'down' },
        { to: 'songpsvpit', dir: 'left' },
        { to: 'phrasesgpvit', dir: 'right' },
        { to: 'projectspcvpit', dir: 'up' },
    ],
    effectsettingspsvxpit: [{ to: 'mixerpsvxpit', dir: 'up' }],
    effectsettingssgpvxit: [{ to: 'mixersgpvxit', dir: 'up' }],
    effectsettingsspcvxpit: [{ to: 'mixerspcvxpit', dir: 'up' }],
    effectsettingsspimtvx: [{ to: 'mixerspimtvx', dir: 'up' }],
    effectsettingsspmivxt: [{ to: 'mixerspmivxt', dir: 'up' }],
    groovessgpvit: [
        { to: 'phrasesgpvit', dir: 'down' },
        { to: 'scalessgpvit', dir: 'up' },
    ],
    'inst.modsspimtv': [{ to: 'tablespimtv', dir: 'down' }],
    'inst.modssppmivt': [
        { to: 'inst.spmivt', dir: 'down' },
        { to: 'instrumentpoolsppmivit', dir: 'up' },
    ],
    'inst.spmivt': [
        { to: 'mixerspmivxt', dir: 'down' },
        { to: 'phrasesgpvit', dir: 'left' },
        { to: 'tablespimtv', dir: 'right' },
        { to: 'inst.modssppmivt', dir: 'up' },
    ],
    'inst.sppmivit': [{ to: 'instrumentpoolsppmivit', dir: 'left' }],
    instrumentpoolsppmivit: [
        { to: 'inst.modssppmivt', dir: 'down' },
        { to: 'inst.sppmivit', dir: 'right' },
    ],
    mixerpsvxpit: [
        { to: 'effectsettingspsvxpit', dir: 'down' },
        { to: 'mixscopepsvxpit', dir: 'right' },
        { to: 'songpsvpit', dir: 'up' },
    ],
    mixersgpvxit: [
        { to: 'effectsettingssgpvxit', dir: 'down' },
        { to: 'mixscopesgpvxit', dir: 'right' },
        { to: 'phrasesgpvit', dir: 'up' },
    ],
    mixerspcvxpit: [
        { to: 'effectsettingsspcvxpit', dir: 'down' },
        { to: 'mixscopespcvxpit', dir: 'right' },
        { to: 'chainspcvpit', dir: 'up' },
    ],
    mixerspimtvx: [
        { to: 'effectsettingsspimtvx', dir: 'down' },
        { to: 'mixscopespimtvx', dir: 'right' },
        { to: 'tablespimtv', dir: 'up' },
    ],
    mixerspmivxt: [
        { to: 'effectsettingsspmivxt', dir: 'down' },
        { to: 'mixscopespmivxt', dir: 'right' },
        { to: 'inst.spmivt', dir: 'up' },
    ],
    mixscopepsvxpit: [{ to: 'mixerpsvxpit', dir: 'left' }],
    mixscopesgpvxit: [{ to: 'mixersgpvxit', dir: 'left' }],
    mixscopespcvxpit: [{ to: 'mixerspcvxpit', dir: 'left' }],
    mixscopespimtvx: [{ to: 'mixerspimtvx', dir: 'left' }],
    mixscopespmivxt: [{ to: 'mixerspmivxt', dir: 'left' }],
    phrasesgpvit: [
        { to: 'mixersgpvxit', dir: 'down' },
        { to: 'chainspcvpit', dir: 'left' },
        { to: 'inst.spmivt', dir: 'right' },
        { to: 'groovessgpvit', dir: 'up' },
    ],
    projectpsvpit: [{ to: 'songpsvpit', dir: 'down' }],
    projectspcvpit: [{ to: 'chainspcvpit', dir: 'down' }],
    scalessgpvit: [{ to: 'groovessgpvit', dir: 'down' }],
    songpsvpit: [
        { to: 'mixerpsvxpit', dir: 'down' },
        { to: 'chainspcvpit', dir: 'right' },
        { to: 'projectpsvpit', dir: 'up' },
    ],
    tablespimtv: [
        { to: 'mixerspimtvx', dir: 'down' },
        { to: 'inst.spmivt', dir: 'left' },
        { to: 'inst.modsspimtv', dir: 'up' },
    ],
}
